version: '3.4'

services:
  snowball:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    expose:
      - 3000
    environment:
      ENV: dev
      DATABASE_URL: ${DB_URL}
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    command: sh -c "npm run migrate && npm run dev"
