name: test

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  compose:
    name: Run docker compose
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes"
          services: |
            db
            snowball